grpc:
  port: {{grpc_port}}
  check:
    host: host.docker.internal
http:
  port: {{http_port}}
  check:
    host: host.docker.internal
consul:
  disabled: false
  scheme: http
  host: 127.0.0.1
  port: 8500
  dc: dc1
  check:
    interval: 10s
apmserver:
  name: elasticsearch-apm-server
  tag: local
  dc: dc1
